### ISSUE TITLE
Many amwg links in acme-viewer lead to "Not Found" page

### ISSUE THREAD

**Issue by muryanto1** [E3SM-Project/processflow#103]
At this link:
https://acme-viewer.llnl.gov/ ... /amwg/0001-0005/

Under “Set Description”

[1] Click on "2 Line plots of annual implied northward transports"
The "Webpage" link leads to "Not Found"

[2] Click on "3 Line plots of DJF, JJA and ANN zonal means"
"CLDTOT_CS2 Total cloud amount" all DJF, JJA and ANN plots say "Not Found"

[3] Click on "4 Vertical countour plots of DJF, JJA and ANN zonal means" 
At the end of the page,
"CFAD_DBZE94_CS	Hydrometeor occurrence " all DJF, JJA and ANN plots say "Not Found"

[4] click on "6 Horizontal vector plots of DJF, JJA and ANN means"
Plot for the followings show "Not Found":
"TTRP Tropopause temperature"
"MEANPTOP Mean cloud top pressure"
"MEANTTOP Mean cloud top tempoerature"
"MEANTAU Mean cloud optical thickness"
"TCLDAREA Total cloud area"
"CLDTOT_CS2 Total cloud amount" 

[5] click on “7 Polar contour and vector plots of DJF, JJA, and ANN means”
Scroll all the way down, 
All plots for CLDTOT_CS2 for Nothern Hemisphere and Southern Hemisphere say “Not Found”

[6] Click on “8 Annual cycle contour plots of zonal means”
“CLDTOT_CS2 Total cloud amount” plot shows “Not Found”

[7] Click on “10 Annual cycle line plots of global means”,
All plots of the followings show “Not Found”:
“Evaporation - precipitation” plot
“Surface Water Flux” plot
“CLDTOT_CS2 Total cloud amount” plot

[8] Click on “12 Vertical profile plots from 17 selected stations”,
All “plot” links on that page shows “Not Found”

[9] Click on “13 Clould simulator plots”, scroll down all the way.
All plots from region plot ARM Southern Great Plains shows “Not Found”

Under “Chemistry Set Description”
[10]
go to “5 Vertical Profile Profiles Comparisons to NOAA Aircraft observations”
3 of the plots say “Not Found”
And Texas shows black screen.

[11] 
Go to “7 Surface observation Scatter Plot Comparisons to IMROVE 
DJF, MAM, SON shows “Not Found”

[12] 
Go to “1 Tables/Chemistry of ANN global budgets”
Global ANN, DJF, JJA all shows “Not Found”

[13]
Click on “2 Vertical Contour Plots contour plots of DJF, MAM, JJA,…”
It shows “Not Found”

[14] 
Click on “4 Column O3 and CO lon/lat Comparions to satellite data”
All the MAM and SON links show “Not Found”
Also all months link show “Not Found”

**Comment by sterlingbaldwin** [comment]
This is because the AMWG package tries to do diagnostics on a bunch of variables that dont exist in E3SM data. I have a fix that removes links to plots that dont exist.
