### ISSUE TITLE
Installation instructions point to acme, not e3sm

### ISSUE THREAD

**Issue by kaabre** [E3SM-Project/processflow#106]
Not a large issue, but thought to point it out:

Installation

conda create --name <YOUR_NEW_ENVIRONMENT> -c acme -c conda-forge -c uvcdat processflow

Shouldn't this point to e3sm instead of acme?  Or will both work?

**Comment by susburrows** [comment]
I also noticed that the README file and project description on github still say "ACME".

**Comment by sterlingbaldwin** [comment]
Thanks, fixed in my latest pull request (hasnt been merged yet).
