### ISSUE TITLE
How to indicate that source directory is local to bypass globus?

### ISSUE THREAD

**Issue by kaabre** [E3SM-Project/processflow#107]
In the documentation it says "If running from local pre-staged data" the source_path key is ignored, but how do I indicate in the cfg file that this should be the case?  By using a local globus ID or something, or is there an additional key to use?

**Comment by sterlingbaldwin** [comment]
Sorry for not answering this before, didnt see the issue. The next version will explicitly contain the option to mark a case as local. For the time being you have to do a little work to make it work.

If you're just running amwg or e3sm_diags, you only need to include the atm files, everything else if for aprime. Land file transfers are just a convenience and arent needed by any diagnostic (yet!).

The directory structure for processflow input/output is like this:

project_path
    |______ input
    |    ....          |____ atm  <- cam.h0 
    |    ....          |____ ice   <- mpascice.hist 
    |    ....          |____ lnd   <- clm2.h0
    |    ....          |____ mpas <- misc files, see below
    |    ....          |____ rest <- restart files, see below
    |    ....          |____ atm
    |______output

If you place your data files in this structure, they should be recognized and the processflow wont try and move any data.

mpas and rest files are one off files needed by aprime diagnostics, if you're not running aprime dont worry about them. If you are, the one of each of the following files need to be in place:

mpas: 
    mpas-cice_in
    mpaso.hist.am.meridionalHeatTransport.0001-02-01.nc <- any meridionalHeatTransport will work
    mpas-o_in
    streams.cice
    streams.ocean

rest:
    mpascice.rst.0002-01-01_00000.nc    <- any mpascice.rst file will work
    mpaso.rst.0002-01-01_00000.nc         <- any mpaso.rst file will work

**Comment by sterlingbaldwin** [comment]
[See here](https://e3sm-project.github.io/processflow/docs/html/configuration.html#data-types) on how to do this in the latest release.
