### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/processflow#108]
processflow 1.1.1 seems to be installing just fine under python 2.7, yay!

I'm seeing the following error when I try to install the python 3.6 version of e3sm-unified:
```
Solving environment: ...working... failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - e3sm-unified=1.2.0 -> processflow[version='>=1.1.1,<1.1.2.0a0'] -> beautiful-soup -> python=3.3 -> xz==5.0.5
  - python=3.6
Use "conda info <package>" to see the dependencies for each package.
```
Addressing this issue is not a high priority, since everyone is used to dealing with the python 2.7 version of e3sm-unified anyway but I would like to move toward having python 3 support (and making the python 3 version the default) whenever possible.

What is the plan for python 3.6 support under processflow?

**Comment by sterlingbaldwin** [comment]
I dont have any specific plans right now for python3 support, but I dont think it would be difficult (but potentially time consuming) to add it. I've identified myself as being stuck in the pythin2.7 rut and would like to dig myself out of it, but its going to have to happen after I've finished the current release. I believe all the packages I depend on have python3 versions, so it might be as easy as going through and making sure all print statements use parens.

**Comment by xylar** [comment]
@sterlingbaldwin, packages used by e3sm-unified are moving quickly toward dropping python 2.7 support.  It would be helpful to have at least one and perhaps a few versions of e3sm-unified that support both python 2.7 and python 3.x before support for python 2.7 goes away completely (which will happen in a bit over a year as I understand it).

Given that situation, I think it might be worth making the transition to python 3 a bit of a higher priority.  Something we can certainly discuss further on the next telecon, if you like.

**Comment by xylar** [comment]
Hey @sterlingbaldwin, just wondering what the timeline might be for moving over the python 3 here?  We're talking of dropping python 2 support in MPAS-Analysis sometime not too long from now and xarray has already started moving in that direction.  So libraries needed by e3sm-unified will gradually stop being supported in python 2 in the next several months.

**Comment by jhkennedy** [comment]
@sterlingbaldwin, any updates on the 2-3 conversion? The latest version of ILAMB (2.4) has dropped python 2 support, so until this happens, we're limited to ILAMB v2.3.1.

**Comment by xylar** [comment]
I should add that @jhkennedy and I have some experience making the conversion to supporting both python 2 and python 3, so we can give you some tips and help out if need be.  Here's the PR where that happened in MPAS-Analysis:
https://github.com/MPAS-Dev/MPAS-Analysis/pull/280

**Comment by jhkennedy** [comment]
Yep, happy to help!

**Comment by sterlingbaldwin** [comment]
I had thought this would be done a while ago, but with the publication stuff Ive been doing its been sitting on the back burner. I can re-prioritize it if its something that's blocking your progress.

**Comment by xylar** [comment]
@sterlingbaldwin and @doutriaux1, 

It looks like `e3sm_to_cmip` doesn't support python 3 yet.  That seems easy to fix.  But it looks like `cmor` doesn't support python 3.   

@doutriaux1, is there any plan to transition to python 3?  Many packages are dropping python 2 support so we're really trapped when it comes to aren't ready to transition yet.
