### ISSUE TITLE
hangs if SFTP is cancelled

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/processflow#120]
After using `CTRL+C` to kill a processflow it has hung for approximately 20 minutes (so far) attempting to terminate the transfer.

`14:43:23: 1/12 files available locally or 8.33%
^C[-] 
----- KEYBOARD INTERRUPT -----
14:54:15: terminating quartz.E3SM.par_split_macrop5min_test.ne30_ne30_sftp_transfer, this may take a moment`

I'm not sure if ~20min + is what it means by "take a moment".

**Comment by AaronDonahue** [comment]
Update: It did eventually end the process.  So it doesn't hang indefinitely.

**Comment by sterlingbaldwin** [comment]
This is a known problem. The sftp handler makes a blocking call when its doing the file transfer and the thread only terminates when the file transfer finishes. Right now it does one file at a time, so if you ctrl-c it has to wait for the file its working on to finish before exiting. An alternative would be for me to spin up a new process for each file transfer which would let me kill it half way through, but that would mean I would have to check the file integrity (md5hash) for every file at start up. This way is kind of annoying to the user, but I think its a lot safer.

**Comment by AaronDonahue** [comment]
Ok, makes sense.  Thanks for responding.

**Comment by sterlingbaldwin** [comment]
An alternative would be for the process flow to kill the transfer and delete the partial file, which would probably feel better to the user since they were trying to curl-c and kill the program. I could just switch to using a subprocess instead of a thread.
