### ISSUE TITLE
Error if dataset not in [[comparisons]] section of run.cfg

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/processflow#121]
I ran into this issue when I was trying to use processflow to compare one dataset to obs and another dataset.  I didn't want the second dataset compared with anything.

In the run.cfg file I only listed the first dataset as follows:
``    [[comparisons]]
        quartz.E3SM.par_split_macrop5min_test.ne30_ne30 = all``

But ran into an error that killed processflow because it was searching for some mention of the other dataset in the comparisons section.  I eventually got around this by adding the other dataset,

``    [[comparisons]]
        quartz.E3SM.par_split_macrop5min_test.ne30_ne30 = all
        master.hybsplit_1800s.ne30_ne30 = all``

But I don't care about the results of the second set of diags, so they will just be wasted calculations.  

It would be nice to have the ability to just list one of the datasets in the [[comparisons]] section, or have a meaningful error message when the job dies.  I didn't figure this out until after a lot of trial and error.

**Comment by sterlingbaldwin** [comment]
Good catch! I never considered that a user wouldnt want the second case to be at the least compared to obs, but in retrospect this is something I should have expected. Thanks for the feedback, this should be a fairly straightforward fix and I'll try to have it out in the next couple days.
