### ISSUE TITLE
timeseries doesn't allow `[[[custom_args]]]`

### ISSUE THREAD

**Issue by jhkennedy** [E3SM-Project/processflow#141]
To specify the charge account on PBS systems, a custom PBS argument needs to be specified vial the `[[[custom_args]]]` subsubsection. For example, specifying the account at NERSC: https://e3sm-project.github.io/processflow/docs/html/quickstart.html#nersc-edison

However, the `[[timeseries]]` `[post-processing]` job doesn't allow for these arguments to be specified (unlike `[[climo]]`). 

This may be an issue for other job types.

**Comment by jhkennedy** [comment]
Interestingly, it looks like timeseries should support `[[[custom_args]]]` because of this bit of logic: https://github.com/E3SM-Project/processflow/blob/2.2.0/jobs/timeseries.py#L21-L25

But, when run on the command line, I get this error: 

```sh
$ python processflow -c joe.cfg -m 1
13:20:26: Entering setup
[-] custom_args is an unsupported timeseries data type
Error in setup, exiting
```

**Comment by sterlingbaldwin** [comment]
Ah, I see the issue. You correctly identified the issue with the verify_config method which should solve this problem.
