### ISSUE TITLE
globus tool versions

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/processflow#143]
`processflow` currently pins versions of the globus tools that aren't on conda-forge.  The options are:
* build those versions on conda-forge
* change `processflow` to use the conda-forge versions

**Comment by xylar** [comment]
@sterlingbaldwin, could you let me know how hard the second option would be?  If it's non-trivial, I'll do the first option.

**Comment by sterlingbaldwin** [comment]
Fixed.
