### ISSUE TITLE
tests folder getting included as a package

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/processflow#153]
It seems like the `tests` directory is getting packaged along with `processflow`.  Because it's not inside the `processflow` package, it gets installed as another package called `tests`.  That's not great both because it's super generic (and causes potential conflicts with other packages that make the same mistake) and because it's not the expected behavior.  It would be better to either move `tests` inside of `processflow` or make sure it's not captured by `setuptools` as part of the package.  (`globus-sdk` seems to do this, too, which is why I even noticed it).

**Comment by sterlingbaldwin** [comment]
I think this is because in the setup.py I use the find_packages helper function instead of explicitly stating which packages should be included. I'll update the setup to only include the processflow package.

**Comment by sterlingbaldwin** [comment]
Fixed in the latest nightly. I was excluding the "test" package (which didnt exist) instead of the "tests" package which did.
