### ISSUE TITLE
More flexibility in specifying years for climo and time series

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/processflow#154]
The current version of processflow does not appear to be very flexible in specifying years for generating climo and time series files.

For example, generate time series files for the entire length of a simulation, but climo files for only a portion of it. Or generate climo file for a specific year range, one that doesn't match the regular pattern of start year and frequency.

**Comment by sterlingbaldwin** [comment]
Thanks Chris, I'll add this to the feature roadmap.

**Comment by golaz** [comment]
Closing this old issue.
