### ISSUE TITLE
Slow local status update

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/processflow#155]
Trying to run processflow in compy on local data. It seems that the 'local status update' is taking a very long time, around 40 to 50 minutes.

**First time**
```
12:13:07: Starting local status update
13:04:25: Local status update complete
```

**Second time**
```
14:06:43: Starting local status update
14:52:27: Local status update complete
```

**Comment by sterlingbaldwin** [comment]
Hey @golaz I think I have a fix for this, could you give me the configuration file you were using so I can make sure it works for your case?

**Comment by golaz** [comment]
@sterlingbaldwin, here is the config file I was using

[run.cfg.txt](https://github.com/E3SM-Project/processflow/files/3532162/run.cfg.txt)

**Comment by sterlingbaldwin** [comment]
Thanks!

**Comment by sterlingbaldwin** [comment]
fixed in the latest.
