### ISSUE TITLE
APrime absolute and relative ts offset

### ISSUE THREAD

**Issue by sterlingbaldwin** [E3SM-Project/processflow#80]
The timeseries plots for aprime should have the start date set to either an absolute date (such as the beginning of the simulation) or a offset from the current year (e.g. running years 50-60, if the offset was -10, it would give 40-60).

**Comment by rljacob** [comment]
Is this really a processflow issue?  If not, open it here:  https://github.com/ACME-Climate/a-prime/issues

**Comment by sterlingbaldwin** [comment]
Its a feature request from Chris for the processflow. The idea is that if we have say 50 years of data split into 5 sets of 10 years, the user should be able to tell pflow to run each instance of aprime from either some absolute date (e.g. year 1), or a relative date from the year set that the instance of aprime is a member of (e.g. -10 years from the year sets start year). The aprime package shouldnt have to make any changes for this to work, pflow just needs to put the data into the input directories and render the aprime run script with the correctly adjusted start years.

**Comment by golaz** [comment]
I think we can close it now since I suggested this initially.
