### ISSUE TITLE
AMWG tar files are empty

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/processflow#92]
I'm not sure if this issue is unique to my runs, but the `0001-0001$CASE-obs.tar` files in my amwg folder are empty at the end of the processflow run.

my amwg_0001-0001.out file has the following message at the time the tarball is meant to be created:

```
MAKING TAR FILE OF DIRECTORY qneg.parsplit_300s.ne30_ne30-qneg.hybsplit_300s.ne30_ne30
tar: qneg.parsplit_300s.ne30_ne30-qneg.hybsplit_300s.ne30_ne30: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
rm: No match.

NORMAL EXIT FROM SCRIPT
```

**Comment by sterlingbaldwin** [comment]
I havent been able to reproduce this, I think something wonky went on with your specific run, if it happens again I'll re-open and examine further.
